// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Artist struct {
	ID   uuid.UUID
	Name string
}

type Author struct {
	ID   uuid.UUID
	Name string
}

type Chapter struct {
	ID                 uuid.UUID
	MangaID            uuid.NullUUID
	Volume             sql.NullString
	Chapter            sql.NullString
	Title              sql.NullString
	TranslatedLanguage sql.NullString
	ExternalUrl        sql.NullString
	PublishAt          sql.NullTime
	ReadableAt         sql.NullTime
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	Pages              sql.NullInt32
	Version            sql.NullInt32
}

type CoverImage struct {
	ID         uuid.UUID
	MangaID    uuid.NullUUID
	FilePath   string
	UploadedAt sql.NullTime
}

type Description struct {
	ID           int32
	MangaID      uuid.NullUUID
	LanguageCode sql.NullString
	Description  sql.NullString
}

type Manga struct {
	ID               uuid.UUID
	Title            sql.NullString
	Description      sql.NullString
	OriginalLanguage sql.NullString
	LastVolume       sql.NullString
	LastChapter      sql.NullString
	Demographic      sql.NullString
	Status           sql.NullString
	Year             sql.NullInt32
	ContentRating    sql.NullString
	State            sql.NullString
	IsLocked         sql.NullBool
	ChapterReset     sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	Version          sql.NullInt32
}

type MangaArtist struct {
	MangaID  uuid.UUID
	ArtistID uuid.UUID
}

type MangaAuthor struct {
	MangaID  uuid.UUID
	AuthorID uuid.UUID
}

type MangaTag struct {
	MangaID uuid.UUID
	TagID   uuid.UUID
}

type MigrationTable struct {
	ID             int32
	MigrationBegin sql.NullTime
	MigrationEnd   sql.NullTime
}

type Tag struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	GroupName   sql.NullString
	Version     sql.NullInt32
}

type Title struct {
	ID           int32
	MangaID      uuid.NullUUID
	LanguageCode sql.NullString
	Title        sql.NullString
}
